### ISSUE TITLE
Too many adds popping up when accessing web 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shahidjmd/google-opt-out-plugin#62]
```
What steps will reproduce the problem?
1.Clicking on an e-mail attachment
2.Searching and accessing  websites
3. Popup adds in the middle of reading material/articles/videos

What is the expected output? What do you see instead? Opt out of all ads.


What version of the product are you using? On what operating system? OS X 
Yosemite 10


Please provide any additional information below.

```

Original issue reported on code.google.com by `mcgeebec...@gmail.com` on 24 Aug 2015 at 5:06

**Comment by shahidjmd** [comment]
optoutplugin/chrome/manifest.json

{
  "name": "IBA Opt-out (by Google)",
  "version": "1.4",
  "description": "Save your interest-based advertising opt-out preference permanently.",
  "manifest_version": 2,
  "icons": { "16": "icon16.png",
             "32": "icon32.png",
             "48": "icon48.png",
             "128": "icon128.png" },
  "background": {
    "scripts": ["background.js"]
  },
  "minimum_chrome_version": "12.0.707.0",
  "permissions": [
    "http://doubleclick.net/",
    "cookies"
  ]
}
